INSERT INTO nombreTabla ( nombreTupla, significadoTupla) VALUES
/* a - abreviar */
('a', 'Primer letra del abecedario castellano. // Vocal. // Preposición que indica dirección.'),
('A','simbolo de amperio'),
('ábaco','m. Aparato que sirve para contar.'),
('abad','m. Superior de un monasterio.'),
('abajo','adv. En la parte inferior.'),
('abalanzar','r. Arrojarse.'),
('abandonar','tr. Dejar desamparado. // Desistir, renunciar.'),
('abanico','m. Aparato para agitar el aire'),
('abaratar','intr. y r. Bajar el precio'),
('abarcar','tr. fig. Acaparar. // Alcanzar con la vista.'),
('abarrotes','m. pl. Artículos de comercio, principalmente comestibles.'),
('abastecer','tr. y r. Proveer.'),
('abatir','tr. Derribar.'),
('abdicar','tr. Renunciar.'),
('abdomen','m. Vientre.'),
('abecedario','m. Serie ordenada de las letras de un idioma.'),
('abedul','m. Árbol de corteza plateada.'),
('abeja','f. Insecto que fabrica miel y cera.'),
('abejorro','m. Insecto zumbador.'),
('abertura','f. Agujero, grieta.'),
('abeto','m. Árbol conífero del que se extrae la trementina.'),
('abierto, ta.','p.p. de abrir. // adj. Llano.'),
('abigarrado, da.','adj. De varios colores mal combinados.'),
('abigeato','m. Hurto de ganado.'),
('abigeo','m. Ladrón de ganado.'),
('abismo','m. Profundidad grande.'),
('abjurar','tr. Renunciar a una religión.'),
('ablandar','tr. Suavizar.'),
('ablución','f. Lavatorio.'),
('abochornar','tr. y r. Sonrojar.'),
('abogado, da.','m. y f. Defensor.'),
('abolengo','m. Ascendencia, linaje, raza.'),
('abolir','tr. Derogar, anular.'),
('abominar','tr. e intr. Condenar y aborrecer.'),
('abonar','tr. Fertilizar la tierra. // Acreditar a cuenta.'),
('abono','m. Pago parcial de una compra a plazos. // Fertilizante.'),
('abordar','tr. e intr. Acercarse a alguien para hablarle.'),
('aborigen','adj. Nativo de un lugar.'),
('aborrecer','tr. Odiar, detestar.'),
('abortar','intr. Parir antes de tiempo. // Fracasar algún proyecto.'),
('aborto','m. Parto prematuro.'),
('abotonar','r. Abrocharse los botones.'),
('abovedado, da.','adj. De forma de bóbeda.'),
('abrasar','tr. y t. Quemar. // Calentar demasiado.'),
('abrasión','f. Desgaste por rozamiento.'),
('abrasivo','m. Producto que sirve para desgastar.'),
('abrazadera','f. Pieza para ceñir.'),
('abrazar','tr. y r. Ceñir con los brazos.'),
('abrazo','m. Acción de abrazar.'),
('abrevadero','m. Sitio donde bebe el ganado.'),
('abreviar','tr. Acortar.'),

/* abreviatura - acéfalo*/
('abreviatura','f. Representción de una palabra con supresión de letras.'),
('abrigar',' tr. y r. Resguardar del frío.'),
('abrigo','m. Defensa contra el frío, el viento etc. // Prenda externa de vestir.'),
('abril','s. Cuarto mes del año.'),
('abrir','tr. y r. Dar paso en lo cerrado. // Inagurar. // Destapar.'),
('abrochar','tr. Asegurar con botones o broches.'),
('abrogar','tr. Abolir, anular.'),
('abrojo','m. Planta de fruto espinoso.'),
('abrumar','tr. y r. Agobiar. // causar pena o cansancio.'),
('abrupto, ta','adj. Escarpado.'),
('absceso','m. Tumor.'),
('absolución','f. Acción de absolver.'),
('absoluto, ta','adj. Independiente.'),
('absolver','tr. Perdonar de algún cargo o acusación. // Perdonar.'),
('absorber','tr. Sorber con fuerza. // Consumir por completo.'),
('absorto, ta','adj. Admirado, pasmado.'),
('abstemio, mia','adj. Que no toma bebidas embriagantes.'),
('abstensión','f. Acción del que se abstiene.'),
('abstener','r. Impedir hacer algo.'),
('abstinencia','f. Acción de abstenerse.'),
;